126-116-114-107-User-Actions
buerokratt/Buerokratt-Chatbot pull request #197
Opened 2023-05-10 21:47 UTC by 1AhmedYasser

2023-05-11 14:24 UTC, Minwasko requested changes

2023-05-11 14:24 UTC, Minwasko commented on DSL.Resql/update-user.sql
> +    id_code = :userIdCode,
This line seems redundant, you are already looking for this row by using `userIdCode`. Please correct me if that's not the case

2023-05-11 14:24 UTC, Minwasko commented on GUI/src/pages/Settings/SettingsUsers/UserModal.tsx
> +      await queryClient.invalidateQueries(['/cs-get-customer-support-agents', 'prod']);
In some cases starting `/` before the `'/cs-get-customer-support-agents'` is present and is not in others, is it optional? 
If that's the case let's decide on if we want to write it or not. I'd say omit it if it's not necessary

2023-05-11 14:24 UTC, Minwasko commented on DSL.Resql/update-user.sql
> +    csa_email = :csa_email
Let's keep it consistent and use camelCase for incoming values in all places. Please also make a respective change on frontend

2023-05-11 16:46 UTC, 1AhmedYasser commented on DSL.Resql/update-user.sql
> +    csa_email = :csa_email
You got a point, but i would keep csa_email for now as it's added in a lot of queries & frontend code, we can do it in a refactor stage, so that we don't break any code at the moment

2023-05-11 16:46 UTC, 1AhmedYasser commented on GUI/src/pages/Settings/SettingsUsers/UserModal.tsx
> +      await queryClient.invalidateQueries(['/cs-get-customer-support-agents', 'prod']);
Done

2023-05-11 16:56 UTC, 1AhmedYasser commented on DSL.Resql/update-user-role.sql
> +SET user_id = :userIdCode,
Done

2023-05-11 16:56 UTC, 1AhmedYasser commented on DSL.Resql/update-user.sql
> +    id_code = :userIdCode,
Done

2023-05-12 06:43 UTC, Minwasko approved these changes

2023-05-15 07:49 UTC, Minwasko approved these changes

2023-05-15 09:54 UTC, PaulaMerle approved these changes

2023-05-15 10:05 UTC, merged