84-106-100-188-Admin-Settings
buerokratt/Buerokratt-Chatbot pull request #198
Opened 2023-05-12 10:11 UTC by 1AhmedYasser

2023-05-15 08:56 UTC, Minwasko requested changes

2023-05-15 08:56 UTC, Minwasko commented on GUI/translations/en/common.json
> +      "description": "Bürokrati automaatne tervitussõnum, mida kuvatakse esimese sõnumina vestlusakna avamisel.",
Please use EN translation here

2023-05-16 00:07 UTC, 1AhmedYasser commented on GUI/src/components/Chat/index.tsx
> -    onStartAService?: (chat: ChatType) => void;
Added it back, git doing some crazy stuff sometimes, it removed 2 lines i added and removed a line i didn't actually remove, weird

2023-05-16 12:23 UTC, Minwasko approved these changes

2023-05-19 09:55 UTC, PaulaMerle approved these changes

2023-05-19 09:56 UTC, merged