Amend Organization Working time
buerokratt/Buerokratt-Chatbot pull request #355
Opened 2023-11-12 23:58 UTC by 1AhmedYasser

2023-11-14 10:58 UTC, baha-a requested changes

2023-11-14 10:58 UTC, baha-a commented on GUI/src/pages/Settings/SettingsWorkingTime/data.tsx
> +    organizationWorkingTimeWeekdays: data.organizationWorkingTimeWeekdays ?? [],
Using _Destructuring operator_ will make the code more readable. 

```js
return {
   ...data,
   // add the properties that you want to rename or apply further processing to, like: 
   organizationClosedOnWeekEnds: data.organizationClosedOnWeekEnds.toString(),
   organizationWorkingTimeWeekdays: data.organizationWorkingTimeWeekdays ?? [],
   // ... etc
}
```

2023-11-14 10:58 UTC, baha-a commented on DSL.Resql/get-organization-working-time.sql
> +   OR key ='organizationTheSameOnAllWorkingDays'
Wouldn't it be more readable to use `IN` instead of `OR`:
```sql
WHERE key IN (
   'organizationMondayWorkingTimeStartISO',
   'organizationMondayWorkingTimeEndISO',
   'organizationTuesdayWorkingTimeStartISO',
   ...

```

2023-11-14 10:58 UTC, baha-a commented on GUI/src/pages/Settings/SettingsWorkingTime/data.tsx
> +        : new Date(),
Please extract this logic into a separate function for better maintainability:

example: 
```js
function convertData(dateAsString?: string | Date): Date {
    return dateAsString ? new Date(dateAsString) : new Date();
}

```
leter:

```js
{
  organizationMondayWorkingTimeStartISO: convertDate(data.organizationMondayWorkingTimeStartISO),
  organizationMondayWorkingTimeEndISO: convertDate(data.organizationMondayWorkingTimeEndISO),
}
```

2023-11-15 22:28 UTC, 1AhmedYasser commented
@baha-a Addressed your comments, kindly check it

2023-11-16 07:41 UTC, baha-a approved these changes
LGTM

2023-11-16 07:49 UTC, PaulaMerle approved these changes

2023-11-16 07:49 UTC, merged