Add chat termination endpoints
buerokratt/Buerokratt-Chatbot pull request #475
Opened 2024-03-28 07:53 UTC by baha-a

Related to:
- #460 

Combined with:
- https://github.com/buerokratt/Chat-Widget/pull/103

2024-04-02 10:56 UTC, 1AhmedYasser requested changes

2024-04-02 10:56 UTC, 1AhmedYasser commented on DSL/Ruuter.public/DSL/POST/remove-chat-from-termination-queue.yml
> +    chatId: "${incoming.body.message.chatId}"
Please remove `.message`, it should be `chatId: "${incoming.body.chatId}"` as you don't pass message from chat widget side

2024-04-02 10:56 UTC, 1AhmedYasser commented on notification-server/src/server.js
> +  await fetch(`${process.env.RUUTER_URL}/end-chat`, {
This part should not end the chat, it should only remove from queue

2024-04-02 10:56 UTC, 1AhmedYasser commented on notification-server/src/server.js
Another part should be added to regularly check for chats in termination queue and check their times, if it for example exceeded 5 seconds, then the chat should be ended and removed from termination queue

2024-04-02 10:56 UTC, 1AhmedYasser commented on DSL/Ruuter.public/DSL/POST/add-chat-to-termination-queue.yml
> +      scheduledForTerminated: ${new Date().toISOString()}
I noticed in database that this entry is added as `yyyy-MM-dd`, it should be date and time as well in order to help when checking the termination queue to remove chats from it

2024-04-04 08:29 UTC, 1AhmedYasser commented
remove from termination queue only works with the first refresh. After that it gets cancelled resulting in the chat being in the termination queue in the database endlessly

2024-04-04 08:59 UTC, 1AhmedYasser requested changes

2024-04-04 08:59 UTC, 1AhmedYasser commented on DSL/Ruuter.public/DSL/POST/add-chat-to-termination-queue.yml
> +    authorRole: ${incoming.body.message.authorRole}
Please add double quotes `authorRole: "${incoming.body.message.authorRole}"`

2024-04-07 15:58 UTC, 1AhmedYasser commented
https://github.com/buerokratt/Buerokratt-Chatbot/assets/26207361/94b2cdfb-f7da-4007-ab44-f44884eba992

@baha-a  There is an Edge case that i found when i was checking the latest changes.

1. Start a chat and forward it to the back-office
2. Close the tab, and wait 5 seconds, the chat will be ended automatically
3. Now start a new chat and forward it to the back-office
4. Now refresh and then close the tab, the chat will not end after 5 seconds and when you open the widget again and then close the tab then the chat will be ended.

In conclusion, if you refresh and then close the tab, then the chat will not end, it only ends if you didn't refresh before closing the tab

2024-04-07 15:59 UTC, 1AhmedYasser requested changes
Please address the edge case i mentioned

2024-04-08 06:51 UTC, baha-a commented
> Please address the edge case i mentioned

This edge case has been resolved. Please review it again at your earliest convenience.

2024-04-08 07:03 UTC, merged